name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Semantic Release
        run: yarn semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
